$ErrorActionPreference = "Stop"

$Python = if ($env:PYTHON) { $env:PYTHON } else { "python" }

& $Python script/00_setup.py
& $Python script/01_verify_sources.py
& $Python script/01_inventory_surveys.py
& $Python script/02_acquire_microdata.py
& $Python script/02_probe_external_repositories.py
& $Python script/44_download_public_external_raw_candidates.py
& $Python script/03_inspect_raw_schemas.py
& $Python script/20_sample_selection_gate.py
& $Python script/21_audit_metadata_variable_quality.py
& $Python script/04_build_household_panel.py
& $Python script/05_construct_outcomes.py
& $Python script/19_probe_validation_reference_sources.py
& $Python script/06_extract_climate.py
& $Python script/18_probe_climate_sources.py
& $Python script/07_merge_microdata_climate.py
& $Python script/08_descriptive_diagnostics.py
& $Python script/09_predictive_ml.py
& $Python script/10_causal_models.py
& $Python script/11_causal_ml_policy_learning.py
& $Python script/12_robustness.py
& $Python script/13_write_reports.py
& $Python script/16_snapshot_public_documentation.py
& $Python script/15_prepare_manual_request_packet.py
& $Python script/27_build_raw_download_intake_package.py
& $Python script/17_audit_raw_downloads.py
& $Python script/22_build_raw_ingestion_plan.py
& $Python script/29_build_raw_variable_verification_protocol.py
& $Python script/33_build_harmonization_recipe_gate.py
& $Python script/30_build_minimum_viable_acquisition_plan.py
& $Python script/23_build_climate_exposure_plan.py
& $Python script/32_build_climate_validation_protocol.py
& $Python script/24_build_outcome_denominator_plan.py
& $Python script/31_build_sdg382_denominator_audit_plan.py
& $Python script/25_build_modeling_identification_plan.py
& $Python script/34_build_mechanism_analysis_protocol.py
& $Python script/35_build_empirical_readiness_dashboard.py
& $Python script/37_build_first_batch_raw_acquisition_checklist.py
& $Python script/39_probe_first_batch_official_raw_access.py
& $Python script/38_build_first_batch_raw_verification_workbook.py
& $Python script/40_build_first_batch_manual_download_handoff.py
& $Python script/41_build_first_batch_public_documentation_audit.py
& $Python script/42_build_first_batch_file_source_traceability.py
& $Python script/43_build_first_batch_merge_key_lineage_plan.py
& $Python script/45_audit_first_batch_raw_value_keys.py
& $Python script/54_audit_alb2002_household_core_merge.py
& $Python script/55_audit_alb2002_provisional_outcome_feasibility.py
& $Python script/60_audit_alb2002_outcome_semantics_raw_values.py
& $Python script/89_audit_alb2002_health_questionnaire_semantics.py
& $Python script/91_audit_alb2002_oop_aggregation_policy.py
& $Python script/92_audit_alb2002_skip_missing_semantics.py
& $Python script/97_audit_alb2002_oop_skip_value_decision.py
& $Python script/93_audit_alb2002_access_need_denominator_policy.py
& $Python script/105_build_alb2002_access_candidate_outcomes.py
& $Python script/94_audit_alb2002_consumption_sdg_denominator_policy.py
& $Python script/96_audit_alb2002_consumption_construction_sources.py
& $Python script/95_audit_alb2002_consumption_aggregate_metadata_crosswalk.py
& $Python script/99_audit_alb2002_period_aligned_che_policy.py
& $Python script/100_audit_alb2002_weight_design_evidence.py
& $Python script/104_audit_alb2002_sample_design_documentation.py
& $Python script/56_audit_alb2002_district_climate_crosswalk.py
& $Python script/64_audit_alb2002_boundary_name_match.py
& $Python script/79_audit_alb2002_boundary_source_resource_search.py
& $Python script/80_audit_alb2002_boundary_geometry_provenance.py
& $Python script/69_audit_alb2002_boundary_source_alternatives.py
& $Python script/70_audit_alb2002_local_geography_artifacts.py
& $Python script/82_audit_alb2002_boundary_manual_source_followup.py
& $Python script/88_audit_alb2002_gadm_boundary_lead.py
& $Python script/81_build_alb2002_boundary_manual_verification_packet.py
& $Python script/90_build_alb2002_minimum_recipe_promotion_packet.py
& $Python script/101_build_alb2002_che_candidate_outcomes.py
& $Python script/106_build_alb2002_uhc_composite_candidate_outcomes.py
& $Python script/102_build_alb2002_analysis_candidate_dataset.py
& $Python script/117_promote_alb2002_harmonized_household_core.py
& $Python script/05_construct_outcomes.py
& $Python script/119_promote_alb2002_limited_financial_outcomes.py
& $Python script/103_build_alb2002_climate_centroid_exposure_candidates.py
& $Python script/107_build_alb2002_climate_shock_candidate_audit.py
& $Python script/118_promote_alb2002_limited_climate_exposures.py
& $Python script/07_merge_microdata_climate.py
& $Python script/120_promote_alb2002_limited_climate_linked.py
& $Python script/108_build_alb2002_climate_outcome_linked_candidate_audit.py
& $Python script/109_build_alb2002_linked_candidate_descriptive_diagnostics.py
& $Python script/90_build_alb2002_minimum_recipe_promotion_packet.py
& $Python script/98_audit_analysis_dataset_promotion_barriers.py
& $Python script/110_build_current_design_scorecard.py
& $Python script/111_audit_alb2002_promotion_gate_delta.py
& $Python script/112_build_alb2002_boundary_blocker_resolution_matrix.py
& $Python script/113_build_alb2002_outcome_blocker_resolution_matrix.py
& $Python script/57_audit_alb2012_raw_core_feasibility.py
& $Python script/58_audit_alb2012_provisional_outcome_feasibility.py
& $Python script/63_audit_alb2012_outcome_semantics_raw_values.py
& $Python script/59_audit_alb2012_timing_geography_exhaustive.py
& $Python script/65_audit_alb2012_questionnaire_timing_fields.py
& $Python script/114_build_alb2012_timing_geography_blocker_resolution_matrix.py
& $Python script/66_audit_albania_legacy_questionnaire_readability.py
& $Python script/67_audit_albania_legacy_questionnaire_timing_fields.py
& $Python script/46_build_alb2005_documented_harmonization_review.py
& $Python script/47_audit_alb2005_household_core_merge.py
& $Python script/48_audit_alb2005_provisional_outcome_feasibility.py
& $Python script/61_audit_alb2005_outcome_semantics_raw_values.py
& $Python script/49_audit_alb2005_timing_geography_exhaustive.py
& $Python script/71_audit_alb2005_required_value_key_evidence.py
& $Python script/72_audit_alb2005_health_questionnaire_semantics.py
& $Python script/73_audit_alb2005_oop_aggregation_policy.py
& $Python script/74_audit_alb2005_skip_missing_semantics.py
& $Python script/75_audit_alb2005_consumption_oop_unit_period.py
& $Python script/76_audit_alb2005_consumption_aggregate_metadata_crosswalk.py
& $Python script/77_audit_alb2005_consumption_component_source_search.py
& $Python script/78_audit_alb2005_timing_geography_source_search.py
& $Python script/51_audit_alb2008_household_core_merge.py
& $Python script/52_audit_alb2008_provisional_outcome_feasibility.py
& $Python script/62_audit_alb2008_outcome_semantics_raw_values.py
& $Python script/53_audit_alb2008_timing_geography_exhaustive.py
& $Python script/50_audit_existing_albania_raw_waves.py
& $Python script/33_build_harmonization_recipe_gate.py
& $Python script/68_build_alb2005_harmonization_value_decision_audit.py
& $Python script/83_build_alb2005_minimum_recipe_promotion_packet.py
& $Python script/84_audit_alb2005_public_fieldwork_geo_metadata.py
& $Python script/85_audit_alb2005_diary_timing_candidates.py
& $Python script/86_audit_alb2005_extracted_module_coverage.py
& $Python script/87_build_albania_first_analysis_promotion_gate.py
& $Python script/115_build_alb2005_fallback_blocker_resolution_matrix.py
& $Python script/116_build_alb2008_fallback_blocker_resolution_matrix.py
& $Python script/35_build_empirical_readiness_dashboard.py
& $Python script/36_build_direct_read_audit_bundle.py
& $Python script/28_audit_python_environment.py
& $Python script/26_build_objective_traceability_audit.py
& $Python script/13_write_reports.py
& $Python script/14_validate_workspace.py

Write-Host "Public metadata/schema pipeline and guarded empirical gates complete. Estimation stages remain blocked until documented raw microdata access and raw value inspection succeed."
