$ErrorActionPreference = "Stop"

$Python = if ($env:PYTHON) { $env:PYTHON } else { "python" }

& $Python script/00_setup.py
& $Python script/01_verify_sources.py
& $Python script/01_inventory_surveys.py
& $Python script/02_acquire_microdata.py
& $Python script/02_probe_external_repositories.py
& $Python script/44_download_public_external_raw_candidates.py
& $Python script/03_inspect_raw_schemas.py
& $Python script/20_sample_selection_gate.py
& $Python script/21_audit_metadata_variable_quality.py
& $Python script/27_build_raw_download_intake_package.py
& $Python script/17_audit_raw_downloads.py
& $Python script/22_build_raw_ingestion_plan.py
& $Python script/29_build_raw_variable_verification_protocol.py
& $Python script/33_build_harmonization_recipe_gate.py
& $Python script/30_build_minimum_viable_acquisition_plan.py
& $Python script/23_build_climate_exposure_plan.py
& $Python script/32_build_climate_validation_protocol.py
& $Python script/24_build_outcome_denominator_plan.py
& $Python script/31_build_sdg382_denominator_audit_plan.py
& $Python script/25_build_modeling_identification_plan.py
& $Python script/34_build_mechanism_analysis_protocol.py
& $Python script/35_build_empirical_readiness_dashboard.py
& $Python script/37_build_first_batch_raw_acquisition_checklist.py
& $Python script/39_probe_first_batch_official_raw_access.py
& $Python script/38_build_first_batch_raw_verification_workbook.py
& $Python script/40_build_first_batch_manual_download_handoff.py
& $Python script/41_build_first_batch_public_documentation_audit.py
& $Python script/42_build_first_batch_file_source_traceability.py
& $Python script/43_build_first_batch_merge_key_lineage_plan.py
& $Python script/45_audit_first_batch_raw_value_keys.py
& $Python script/121_build_country_wave_promotion_registry.py
& $Python script/122_build_priority_promotion_acquisition_plan.py
& $Python script/123_probe_priority_official_raw_access.py
& $Python script/124_build_priority_raw_intake_gate.py
& $Python script/128_build_priority_archive_member_preflight.py
& $Python script/125_build_priority_climate_linkage_preflight.py
& $Python script/126_build_priority_raw_verification_workbook.py
& $Python script/129_build_priority_manual_verification_decision_gate.py
& $Python script/130_build_priority_raw_package_receipt_ledger.py
& $Python script/131_build_priority_official_download_dossier.py
& $Python script/133_build_priority_public_documentation_receipt.py
& $Python script/135_build_priority_official_metadata_evidence_extract.py
& $Python script/136_build_priority_credentialed_raw_acquisition_ledger.py
& $Python script/137_probe_priority_official_endpoint_matrix.py
& $Python script/138_probe_priority_core_file_endpoint_matrix.py
& $Python script/139_build_priority_threshold_acquisition_campaign.py
& $Python script/140_build_priority_first_pass_variable_review_queue.py
& $Python script/141_build_priority_download_execution_packet.py
& $Python script/142_build_priority_lsms_isa_alignment_audit.py
& $Python script/143_build_priority_lsms_isa_refocused_acquisition_queue.py
& $Python script/146_build_priority_lsms_isa_public_documentation_receipt.py
& $Python script/147_build_priority_lsms_isa_variable_evidence_matrix.py
& $Python script/144_build_priority_lsms_isa_raw_package_intake_packet.py
& $Python script/145_build_priority_lsms_isa_archive_member_preflight.py
& $Python script/149_build_priority_lsms_isa_raw_value_verification_workbook.py
& $Python script/150_build_priority_lsms_isa_raw_package_receipt_checklist.py
& $Python script/152_build_priority_lsms_isa_credentialed_raw_acquisition_workbench.py
& $Python script/153_validate_priority_lsms_isa_official_file_receipt.py
& $Python script/154_build_priority_lsms_isa_threshold_download_sequence.py
& $Python script/155_build_priority_lsms_isa_minimum_batch_raw_intake_guide.py
& $Python script/156_probe_priority_lsms_isa_minimum_batch_endpoint_refresh.py
& $Python script/157_build_priority_lsms_isa_received_raw_schema_audit.py
& $Python script/158_build_priority_lsms_isa_received_raw_value_profile.py
& $Python script/159_build_priority_lsms_isa_received_raw_semantics_review.py
& $Python script/160_build_mwi2004_raw_requirement_verification.py
& $Python script/162_build_mwi2004_health_access_label_skip_decisions.py
& $Python script/163_build_mwi2004_health_exception_audit.py
& $Python script/164_build_mwi2004_health_access_construction_policy.py
& $Python script/165_build_mwi2004_financial_protection_construction_policy.py
& $Python script/189_build_mwi2004_sdg382_discretionary_budget_parameter_audit.py
& $Python script/190_build_mwi2004_sdg382_external_parameter_source_ledger.py
& $Python script/191_build_mwi2004_sdg382_candidate_classification_precheck.py
& $Python script/192_build_mwi2004_sdg382_official_denominator_rule_audit.py
& $Python script/166_build_mwi2004_timing_geography_linkage_policy.py
& $Python script/167_build_mwi2004_access_person_key_resolution_policy.py
& $Python script/168_build_mwi2004_missing_units_recall_skip_policy.py
& $Python script/161_build_mwi2004_requirement_acceptance_decisions.py
& $Python script/169_build_mwi2004_chirps_admin2_route_policy.py
& $Python script/170_extract_mwi2004_chirps_admin2_exposures.py
& $Python script/171_build_mwi2004_promoted_household_climate_dataset.py
& $Python script/132_build_priority_analysis_dataset_synthesis_blueprint.py
& $Python script/134_build_priority_country_wave_promotion_packets.py
& $Python script/148_build_priority_lsms_isa_country_wave_promotion_packets.py
& $Python script/151_refresh_refocused_promoted_country_wave_registry.py
& $Python script/127_enforce_promoted_data_gate.py
& $Python script/172_build_priority_lsms_isa_next_raw_package_action_packet.py
& $Python script/174_build_priority_lsms_isa_incoming_raw_package_router.py
& $Python script/175_build_priority_lsms_isa_threshold_gap_control_panel.py
& $Python script/176_build_priority_lsms_isa_manual_download_packets.py
& $Python script/177_build_priority_lsms_isa_manual_download_progress_tracker.py
& $Python script/178_build_priority_lsms_isa_post_download_validation_runner.py
& $Python script/179_build_priority_lsms_isa_manual_download_execution_board.py
& $Python script/180_build_priority_lsms_isa_credentialed_download_handoff.py
& $Python script/181_probe_priority_lsms_isa_resource_download_routes.py
& $Python script/182_build_priority_lsms_isa_download_acceptance_matrix.py
& $Python script/183_build_priority_lsms_isa_local_target_readmes.py
& $Python script/184_build_priority_lsms_isa_minimum_batch_raw_value_queue.py
& $Python script/185_build_priority_lsms_isa_target_folder_receipt_smoke_test.py
& $Python script/186_build_priority_lsms_isa_threshold_replacement_plan.py
& $Python script/187_build_priority_lsms_isa_minimum_batch_climate_linkage_review_queue.py
& $Python script/188_build_priority_lsms_isa_local_stray_raw_package_locator.py
& $Python script/173_build_priority_lsms_isa_promotion_gate_dashboard.py
& $Python script/193_build_priority_lsms_isa_minimum_batch_promotion_unlock_board.py
& $Python script/36_build_direct_read_audit_bundle.py
& $Python script/28_audit_python_environment.py
& $Python script/26_build_objective_traceability_audit.py
& $Python script/14_validate_workspace.py

Write-Host "Dataset-promotion pipeline complete. Modeling remains blocked until promoted_country_wave_registry.csv reaches the 6-country, 10-wave, and accepted CHIRPS/ERA5 thresholds."
